import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getFirestore, collection, doc, addDoc, setDoc, deleteDoc, onSnapshot, getDocs, query, orderBy } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyDiaAHF0iceYJNlSDKFKtHKnCETeMCW8IA',authDomain:'no32-player-stats.firebaseapp.com',projectId:'no32-player-stats',storageBucket:'no32-player-stats.firebasestorage.app',messagingSenderId:'934416639889',appId:'1:934416639889:web:cd0e319fa86c1acb3fdc30'};
let app,db,auth,cloud=true,user=null;
try{app=initializeApp(firebaseConfig);db=getFirestore(app);auth=getAuth(app)}catch(e){cloud=false;console.warn(e)}
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const state={players:[],games:[],stats:[],tab:'home',selectedPlayer:localStorage.getItem('r32_selected_player')||'',selectedScope:'game',selectedValue:'',editingPlayer:null,editingGame:null,editingStat:null,authOpen:false};
const localKey='r32_complete_local_v27';
function localLoad(){try{const d=JSON.parse(localStorage.getItem(localKey)||'{}');state.players=d.players||[];state.games=d.games||[];state.stats=d.stats||[]}catch{}}
function localSave(){localStorage.setItem(localKey,JSON.stringify({players:state.players,games:state.games,stats:state.stats}))}
function uid(){return 'id_'+Math.random().toString(36).slice(2)+Date.now().toString(36)}
function n(v){return Number(v)||0}function pct(m,a){return a?((m/a)*100):0}function f(v,d=1){return (Number(v)||0).toFixed(d).replace(/\.0$/,'')}function dateMonth(d){return d?d.slice(0,7):''}function dateYear(d){return d?d.slice(0,4):''}
function selectedPlayer(){return state.players.find(p=>p.id===state.selectedPlayer)||state.players[0]||null}
function ensureSelected(){if(!state.selectedPlayer && state.players[0]) state.selectedPlayer=state.players[0].id;localStorage.setItem('r32_selected_player',state.selectedPlayer||'')}
function status(t,ok=false){const el=$('#cloudStatus'); if(el){el.textContent=t; el.style.color=ok?'#45e39d':'#9ca8cd'}}
function resultMark(g){const a=n(g.ownScore),b=n(g.oppScore); if(a>b)return {m:'○',c:'result-win'}; if(a===b&& (a||b))return {m:'△',c:'result-draw'}; if(a||b)return {m:'×',c:'result-loss'}; return {m:'-',c:''}}
function scoreText(g){return (g.ownScore!==undefined&&g.oppScore!==undefined)?`${n(g.ownScore)}-${n(g.oppScore)}`:'--'}
function gameTitle(g){return `${g.date||''} vs ${g.opponent||''}`}
function statGame(s){return state.games.find(g=>g.id===s.gameId)||{}}
function statPlayer(s){return state.players.find(p=>p.id===s.playerId)||{}}
function calc(rows){const t={q:0,pa2:0,pm2:0,pa3:0,pm3:0,fta:0,ftm:0,ast:0,or:0,dr:0,pk:0,ds:0,stlOther:0,blk:0,pmiss:0,dmiss:0,cmiss:0,vio:0,toOther:0};rows.forEach(s=>{const g=statGame(s);t.q+=n(g.quarters);['pa2','pm2','pa3','pm3','fta','ftm','ast','or','dr','pk','ds','stlOther','blk','pmiss','dmiss','cmiss','vio','toOther'].forEach(k=>t[k]+=n(s[k]))});t.games=t.q/4;t.fga=t.pa2+t.pa3;t.fgm=t.pm2+t.pm3;t.reb=t.or+t.dr;t.stl=t.pk+t.ds+t.stlOther;t.to=t.pmiss+t.dmiss+t.cmiss+t.vio+t.toOther;return t}
function perGame(t,k){return t.games? t[k]/t.games:0}function perMadeAttempt(t,m,a){return `${f(perGame(t,a))} / ${f(perGame(t,m))}`}
function statMatrix(t,{pc=false}={}){const pg=t.games||0; const cells=[
 {lab:'2PA / 2PM / 2P%',main:perMadeAttempt(t,'pm2','pa2'),sub:`${f(pct(t.pm2,t.pa2))}%`,p:pct(t.pm2,t.pa2)},
 {lab:'3PA / 3PM / 3P%',main:perMadeAttempt(t,'pm3','pa3'),sub:`${f(pct(t.pm3,t.pa3))}%`,p:pct(t.pm3,t.pa3)},
 {lab:'FGA / FGM / FG%',main:perMadeAttempt(t,'fgm','fga'),sub:`${f(pct(t.fgm,t.fga))}%`,p:pct(t.fgm,t.fga)},
 {lab:'FTA / FTM / FT%',main:perMadeAttempt(t,'ftm','fta'),sub:`${f(pct(t.ftm,t.fta))}%`,p:pct(t.ftm,t.fta)},
 {lab:'AST',main:f(perGame(t,'ast')),sub:'アシスト'},
 {lab:'BLK',main:f(perGame(t,'blk')),sub:'ブロック'}
 ];
 return `<div class="stats-matrix ${pc?'compact-pc':''}">${cells.map(c=>`<div class="metric ${pc&&c.p!==undefined?'with-ring':''}"><div><div class="label">${c.lab}</div><div class="main">${c.main}</div><div class="sub">${c.sub}</div></div>${pc&&c.p!==undefined?`<div class="ring" style="--p:${Math.min(100,c.p)}" data-p="${f(c.p,0)}%"></div>`:''}</div>`).join('')}</div>`}
function breakdown(title,items){return `<div class="breakdown"><h4>${title}</h4><div class="break-grid">${items.map(i=>`<div class="break-item"><strong>${f(i.v)}</strong><span>${i.name}</span></div>`).join('')}</div></div>`}
function breakdowns(t){return `<div class="pc-breaks">${breakdown('STL内訳',[{name:'合計',v:t.stl},{name:'パスカット',v:t.pk},{name:'ドリブルカット',v:t.ds},{name:'その他',v:t.stlOther}])}${breakdown('REB内訳',[{name:'合計',v:t.reb},{name:'オフェンス',v:t.or},{name:'ディフェンス',v:t.dr}])}${breakdown('TO内訳',[{name:'合計',v:t.to},{name:'パスミス',v:t.pmiss},{name:'ドリブルミス',v:t.dmiss},{name:'キャッチミス',v:t.cmiss},{name:'バイオレーション',v:t.vio},{name:'その他',v:t.toOther}])}</div>`}
function render(){ensureSelected();renderNav();renderHome();renderPlayers();renderGames();renderStats();renderSettings();$$('.tab-page').forEach(p=>p.classList.remove('active'));$(`#tab-${state.tab}`)?.classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab))}
function renderNav(){$$('.nav-btn').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()})}
function homeRows(){const p=selectedPlayer();return p?state.stats.filter(s=>s.playerId===p.id):[]}
function renderHome(){const p=selectedPlayer();const t=calc(homeRows());const authAction=user?`<button class="btn" onclick="R32.goInput()">＋ 試合を登録</button><button class="btn secondary" onclick="R32.logout()">ログアウト</button>`:`<button class="btn" onclick="R32.openAuth()">ログイン</button>`;$('#tab-home').innerHTML=`<div class="card glass"><div class="player-head"><div><div class="player-name">${p?`No.${p.number||'-'} ${p.name||''}`:'選手未選択'}</div><div class="player-meta">${p?[p.position,p.grade,p.height?`${p.height}cm`:null].filter(Boolean).join(' / '):'選手を登録してください'}</div></div></div><div class="home-action">${authAction}</div>${state.authOpen&&!user?authForm():''}<div class="avg-head"><h3>1試合平均（全試合）</h3><div class="converted">換算 ${f(t.games)} 試合</div></div>${statMatrix(t,{pc:true})}${breakdowns(t)}</div><div class="card" style="margin-top:14px"><div class="section-title"><h2>最近の試合</h2></div><div class="game-list">${state.games.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,5).map(gameRow).join('')||'<div class="empty">まだ試合がありません</div>'}</div></div>`}
function authForm(){return `<div class="auth-box"><div class="form-row"><div class="field"><label>メール</label><input id="loginEmail" type="email" autocomplete="email"></div><div class="field"><label>パスワード</label><input id="loginPassword" type="password" autocomplete="current-password"></div></div><button class="btn secondary" onclick="R32.login()">ログイン実行</button></div>`}
function renderPlayers(){const can=!!user;$('#tab-players').innerHTML=`<div class="card"><div class="section-title"><h2>選手</h2><small>${can?'管理者モード':'閲覧のみ'}</small></div>${can?playerForm():''}<div class="game-list" style="margin-top:12px">${state.players.map(p=>`<div class="game-row"><div class="game-bottom"><span>No.${p.number||'-'} ${p.name}</span><span>${p.position||''}</span></div><div class="game-top"><span>${p.grade||''} ${p.height?`${p.height}cm`:''}</span><span>${can?`<button class="btn secondary" onclick="R32.editPlayer('${p.id}')">修正</button> <button class="btn danger" onclick="R32.deletePlayer('${p.id}')">削除</button>`:''}</span></div></div>`).join('')||'<div class="empty">選手が未登録です</div>'}</div></div>`}
function playerForm(){const p=state.editingPlayer?state.players.find(x=>x.id===state.editingPlayer)||{}:{};return `<div class="form"><div class="form-row"><div class="field"><label>選手名</label><input id="pName" value="${p.name||''}"></div><div class="field"><label>背番号</label><input id="pNumber" value="${p.number||''}"></div></div><div class="form-row"><div class="field"><label>ポジション</label><input id="pPos" value="${p.position||''}"></div><div class="field"><label>身長</label><input id="pHeight" type="number" value="${p.height||''}"></div></div><div class="field"><label>学年</label><input id="pGrade" value="${p.grade||''}"></div><button class="btn" onclick="R32.savePlayer()">${p.id?'選手を更新':'選手を登録'}</button></div>`}
function renderGames(){const can=!!user;$('#tab-games').innerHTML=`<div class="card"><div class="section-title"><h2>試合</h2><small>${can?'試合登録・修正':'閲覧のみ'}</small></div>${can?gameForm():''}<div class="game-list" style="margin-top:12px">${state.games.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(g=>`${gameRow(g)}${can?`<div style="margin:-8px 0 8px 8px"><button class="btn secondary" onclick="R32.editGame('${g.id}')">修正</button> <button class="btn danger" onclick="R32.deleteGame('${g.id}')">削除</button></div>`:''}`).join('')||'<div class="empty">試合が未登録です</div>'}</div></div>${can?statInputCard():''}`}
function gameForm(){const g=state.editingGame?state.games.find(x=>x.id===state.editingGame)||{}:{};return `<div class="form"><div class="form-row"><div class="field"><label>年月日</label><input id="gDate" type="date" value="${g.date||''}"></div><div class="field"><label>Q数</label><input id="gQ" type="number" value="${g.quarters||4}"></div></div><div class="form-row"><div class="field"><label>対戦チーム</label><input id="gOpp" value="${g.opponent||''}"></div><div class="field"><label>大会名</label><input id="gTournament" value="${g.tournament||''}"></div></div><div class="form-row"><div class="field"><label>自チーム得点</label><input id="gOwn" type="number" value="${g.ownScore||''}"></div><div class="field"><label>相手得点</label><input id="gOppScore" type="number" value="${g.oppScore||''}"></div></div><button class="btn" onclick="R32.saveGame()">${g.id?'試合を更新':'試合を登録'}</button></div>`}
function statInputCard(){const s=state.editingStat?state.stats.find(x=>x.id===state.editingStat)||{}:{};return `<div class="card" style="margin-top:14px"><div class="section-title"><h2>スタッツ入力</h2><small>試合 → 選手 → 個人スタッツ</small></div><div class="form"><div class="form-row"><div class="field"><label>試合</label><select id="sGame">${state.games.map(g=>`<option value="${g.id}" ${s.gameId===g.id?'selected':''}>${g.date||''} vs ${g.opponent||''}</option>`).join('')}</select></div><div class="field"><label>選手</label><select id="sPlayer">${state.players.map(p=>`<option value="${p.id}" ${s.playerId===p.id?'selected':''}>No.${p.number||''} ${p.name}</option>`).join('')}</select></div></div>${inputGrid(['pa2:2PA','pm2:2PM','pa3:3PA','pm3:3PM','fta:FTA','ftm:FTM','ast:AST','blk:BLK','or:OR','dr:DR','pk:パスカット','ds:ドリブルカット','stlOther:STLその他','pmiss:パスミス','dmiss:ドリブルミス','cmiss:キャッチミス','vio:バイオレーション','toOther:TOその他'],s)}${inputGrid(['youtube1:YouTube URL 1','youtube2:YouTube URL 2','youtube3:YouTube URL 3','youtube4:YouTube URL 4'],s,'url')}<button class="btn" onclick="R32.saveStat()">${s.id?'スタッツを更新':'スタッツを登録'}</button></div></div>`}
function inputGrid(items,obj,type='number'){return `<div class="grid two">${items.map(x=>{const [id,lab]=x.split(':');return `<div class="field"><label>${lab}</label><input id="${id}" type="${type}" value="${obj[id]||''}"></div>`}).join('')}</div>`}
function gameRow(g){const r=resultMark(g);return `<div class="game-row"><div class="game-top"><span>${g.date||'日付未入力'}</span><span>${g.tournament||'大会未入力'}</span></div><div class="game-bottom"><span>vs ${g.opponent||'未入力'} / ${n(g.quarters)}Q</span><span class="${r.c}">${r.m} ${scoreText(g)}</span></div></div>`}
function renderStats(){const p=selectedPlayer();const selected=state.selectedPlayer||'';let rows=state.stats.filter(s=>s.playerId===selected);const scope=state.selectedScope;const options=scopeOptions(scope,rows);if(!state.selectedValue&&options[0])state.selectedValue=options[0].value;rows=filterRows(scope,state.selectedValue,rows);const t=calc(rows);const title=scopeTitle(scope,state.selectedValue,rows);$('#tab-stats').innerHTML=`<div class="card"><div class="section-title"><h2>スタッツ</h2><small>${p?`No.${p.number||'-'} ${p.name}`:'選手未選択'}</small></div><div class="form-row"><div class="field"><label>選手</label><select id="selectPlayer" onchange="R32.selectPlayer(this.value)">${state.players.map(pl=>`<option value="${pl.id}" ${selected===pl.id?'selected':''}>No.${pl.number||''} ${pl.name}</option>`).join('')}</select></div><div class="field"><label>対象</label><select id="selectValue" onchange="R32.selectValue(this.value)">${options.map(o=>`<option value="${o.value}" ${state.selectedValue===o.value?'selected':''}>${o.label}</option>`).join('')}</select></div></div><div class="pill-tabs">${['game:試合','tournament:大会','day:日','month:月','year:年'].map(x=>{const [v,l]=x.split(':');return `<button class="${scope===v?'active':''}" onclick="R32.setScope('${v}')">${l}</button>`}).join('')}</div><div class="avg-head"><h3>${title}</h3><div class="converted">総Q ${f(t.q)} / 換算 ${f(t.games)} 試合</div></div>${(scope!=='year'&&scope!=='game')?`<div class="game-list" style="margin-bottom:12px">${[...new Set(rows.map(r=>r.gameId))].map(id=>gameRow(state.games.find(g=>g.id===id)||{})).join('')}</div>`:''}${scope==='game'?gameDetail(rows):summaryBlock(t,true)}</div>`}
function summaryBlock(t,pc=false){return `${statMatrix(t,{pc})}${breakdowns(t)}`}
function gameDetail(rows){const s=rows[0]||{};const g=statGame(s);const t=calc(rows);const y=[s.youtube1,s.youtube2,s.youtube3,s.youtube4].filter(Boolean);return `${gameRow(g)}${summaryBlock(t,true)}${y.length?`<div class="breakdown"><h4>YouTube動画</h4><div class="grid two">${y.map((url,i)=>`<a class="btn secondary" href="${url}" target="_blank" rel="noopener">動画${i+1}を見る</a>`).join('')}</div></div>`:''}`}
function scopeOptions(scope,rows){if(scope==='game')return rows.map(s=>({value:s.id,label:gameTitle(statGame(s))})); if(scope==='tournament')return [...new Set(rows.map(s=>statGame(s).tournament).filter(Boolean))].map(v=>({value:v,label:v})); if(scope==='day')return [...new Set(rows.map(s=>statGame(s).date).filter(Boolean))].map(v=>({value:v,label:v})); if(scope==='month')return [...new Set(rows.map(s=>dateMonth(statGame(s).date)).filter(Boolean))].map(v=>({value:v,label:v})); if(scope==='year')return [...new Set(rows.map(s=>dateYear(statGame(s).date)).filter(Boolean))].map(v=>({value:v,label:v})); return []}
function filterRows(scope,val,rows){if(!val)return rows;if(scope==='game')return rows.filter(s=>s.id===val); if(scope==='tournament')return rows.filter(s=>statGame(s).tournament===val); if(scope==='day')return rows.filter(s=>statGame(s).date===val); if(scope==='month')return rows.filter(s=>dateMonth(statGame(s).date)===val); if(scope==='year')return rows.filter(s=>dateYear(statGame(s).date)===val);return rows}
function scopeTitle(scope,val,rows){if(scope==='game'){const g=statGame(rows[0]||{});return g.opponent?`vs ${g.opponent}`:'試合別'}return val||'対象データなし'}
function renderSettings(){$('#tab-settings').innerHTML=`<div class="card"><div class="section-title"><h2>設定</h2></div><p class="player-meta">ログイン状態：${user?user.email:'未ログイン'}</p><p class="player-meta">登録ボタンはログイン時のみ表示されます。</p><button class="btn secondary" onclick="R32.exportData()">バックアップを書き出し</button></div>`}
async function saveDoc(col,id,data){if(user&&cloud){if(id)await setDoc(doc(db,col,id),data,{merge:true});else await addDoc(collection(db,col),data)}else{data.id=id||uid();let arr=state[col];const idx=arr.findIndex(x=>x.id===data.id);idx>=0?arr[idx]=data:arr.push(data);localSave();render()}}
async function delDoc(col,id){if(user&&cloud)await deleteDoc(doc(db,col,id));else{state[col]=state[col].filter(x=>x.id!==id);localSave();render()}}
function collect(ids){const o={};ids.forEach(id=>o[id]=$('#'+id)?.value||'');return o}
window.R32={
 openAuth(){state.authOpen=!state.authOpen;render()},
 async login(){try{await signInWithEmailAndPassword(auth,$('#loginEmail').value,$('#loginPassword').value);state.authOpen=false}catch(e){alert('ログインできません: '+e.message)}},
 async logout(){await signOut(auth)},
 goInput(){state.tab='games';render();setTimeout(()=>document.querySelector('#tab-games .card')?.scrollIntoView({behavior:'smooth'}),50)},
 async savePlayer(){if(!user)return alert('ログインが必要です');const data={...collect(['pName','pNumber','pPos','pHeight','pGrade']),name:$('#pName').value,number:$('#pNumber').value,position:$('#pPos').value,height:$('#pHeight').value,grade:$('#pGrade').value};const id=state.editingPlayer;data.id=id||uid();await saveDoc('players',id,data);state.editingPlayer=null;},
 editPlayer(id){state.editingPlayer=id;render()},
 async deletePlayer(id){if(confirm('選手と関連スタッツを削除しますか？')){await delDoc('players',id);for(const s of state.stats.filter(x=>x.playerId===id))await delDoc('stats',s.id)}},
 async saveGame(){if(!user)return alert('ログインが必要です');const id=state.editingGame;const data={id:id||uid(),date:$('#gDate').value,quarters:n($('#gQ').value),opponent:$('#gOpp').value,tournament:$('#gTournament').value,ownScore:n($('#gOwn').value),oppScore:n($('#gOppScore').value)};await saveDoc('games',id,data);state.editingGame=null},
 editGame(id){state.editingGame=id;render()},
 async deleteGame(id){if(confirm('試合と関連スタッツを削除しますか？')){await delDoc('games',id);for(const s of state.stats.filter(x=>x.gameId===id))await delDoc('stats',s.id)}},
 async saveStat(){if(!user)return alert('ログインが必要です');const ids=['pa2','pm2','pa3','pm3','fta','ftm','ast','blk','or','dr','pk','ds','stlOther','pmiss','dmiss','cmiss','vio','toOther','youtube1','youtube2','youtube3','youtube4'];const id=state.editingStat;const data={id:id||uid(),gameId:$('#sGame').value,playerId:$('#sPlayer').value};ids.forEach(k=>data[k]=k.startsWith('youtube')?$('#'+k).value:n($('#'+k).value));await saveDoc('stats',id,data);state.editingStat=null;state.selectedPlayer=data.playerId;state.selectedScope='game';state.selectedValue=data.id;localStorage.setItem('r32_selected_player',data.playerId)},
 selectPlayer(id){state.selectedPlayer=id;state.selectedValue='';localStorage.setItem('r32_selected_player',id);render()},
 setScope(sc){state.selectedScope=sc;state.selectedValue='';render()},
 selectValue(v){state.selectedValue=v;render()},
 exportData(){const blob=new Blob([JSON.stringify({players:state.players,games:state.games,stats:state.stats},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='r32-backup.json';a.click()}
};
async function initCloud(){if(!cloud){localLoad();status('ローカルモード');render();return}onAuthStateChanged(auth,u=>{user=u;status(u?'クラウド接続済み・ログイン中':'クラウド接続済み',true);render()});['players','games','stats'].forEach(col=>onSnapshot(collection(db,col),snap=>{state[col]=snap.docs.map(d=>({id:d.id,...d.data()}));ensureSelected();render()},err=>{console.error(err);status('クラウド接続エラー');localLoad();render()}))}
initCloud();render();
