import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { getFirestore, collection, addDoc, setDoc, doc, deleteDoc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDiaAHF0iceYJNlSDKFKtHKnCETeMCW8IA',authDomain:'no32-player-stats.firebaseapp.com',projectId:'no32-player-stats',storageBucket:'no32-player-stats.firebasestorage.app',messagingSenderId:'934416639889',appId:'1:934416639889:web:cd0e319fa86c1acb3fdc30'};
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app);
let players=[], games=[], videos=[], currentUser=null, editId=null;
let selectedPlayer=localStorage.getItem('r32_selected_player')||'';
const $=id=>document.getElementById(id), n=v=>Number(v||0), pct=(m,a)=>a?`${(m/a*100).toFixed(1)}%`:'0.0%';
const qs=(s,r=document)=>Array.from(r.querySelectorAll(s));
function show(view){qs('.view').forEach(v=>v.classList.remove('active'));$(view).classList.add('active');qs('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('pageTitle').textContent={home:'ホーム',players:'選手',games:'試合管理',analysis:'分析',videos:'動画',settings:'設定',input:'試合入力'}[view]||view; if(view==='input') fillPlayerSelects(); renderAll();}
qs('.nav-btn').forEach(b=>b.onclick=()=>show(b.dataset.view)); $('goInputBtn').onclick=()=>{editId=null; clearForm(); show('input')}; $('cancelEditBtn').onclick=()=>show('games');
$('loginBtn').onclick=async()=>{ if(currentUser){await signOut(auth);return} const email=prompt('メールアドレス'); const pass=prompt('パスワード'); if(email&&pass) await signInWithEmailAndPassword(auth,email,pass).catch(e=>alert(e.message)); };
onAuthStateChanged(auth,u=>{currentUser=u;$('loginBtn').textContent=u?'ログアウト':'ログイン';$('cloudStatus').textContent=u?'🟢 クラウド接続済み':'🟢 閲覧モード';});
function listen(name,setter){onSnapshot(collection(db,name),snap=>{setter(snap.docs.map(d=>({id:d.id,...d.data()}))); renderAll();},e=>{$('cloudStatus').textContent='🔴 接続エラー';console.error(e)});} listen('players',v=>players=v); listen('games',v=>games=v); listen('videos',v=>videos=v);
$('savePlayerBtn').onclick=async()=>{if(!currentUser)return alert('ログインしてください'); await addDoc(collection(db,'players'),{name:$('playerName').value,no:$('playerNo').value,pos:$('playerPos').value,grade:$('playerGrade').value,height:$('playerHeight').value,createdAt:serverTimestamp()}); ['playerName','playerNo','playerPos','playerGrade','playerHeight'].forEach(id=>$(id).value='')};
function getForm(){let ids=['statPlayer','date','opponent','tournament','venue','quarters','myScore','oppScore','twopa','twopm','threepa','threepm','fta','ftm','ast','or','dr','pk','ds','blk','pm','dm','cm','vio','oth']; let o={}; ids.forEach(id=>o[id]=$(id).value); ['quarters','myScore','oppScore','twopa','twopm','threepa','threepm','fta','ftm','ast','or','dr','pk','ds','blk','pm','dm','cm','vio','oth'].forEach(k=>o[k]=n(o[k])); o.playerId=o.statPlayer; delete o.statPlayer; o.updatedAt=serverTimestamp(); return o;}
function clearForm(){editId=null; $('inputTitle').textContent='試合スタッツ入力'; ['date','opponent','tournament','venue','myScore','oppScore','twopa','twopm','threepa','threepm','fta','ftm','ast','or','dr','pk','ds','blk','pm','dm','cm','vio','oth'].forEach(id=>$(id).value=''); $('quarters').value=4;}
$('saveGameBtn').onclick=async()=>{if(!currentUser)return alert('ログインしてください'); const data=getForm(); if(!data.playerId)return alert('選手を選択してください'); selectedPlayer=data.playerId; localStorage.setItem('r32_selected_player',selectedPlayer); if(editId) await setDoc(doc(db,'games',editId),data,{merge:true}); else await addDoc(collection(db,'games'),{...data,createdAt:serverTimestamp()}); clearForm(); show('games')};
function editGame(id){let g=games.find(x=>x.id===id); if(!g)return; editId=id; $('inputTitle').textContent='試合スタッツ修正'; const map={statPlayer:'playerId'}; ['statPlayer','date','opponent','tournament','venue','quarters','myScore','oppScore','twopa','twopm','threepa','threepm','fta','ftm','ast','or','dr','pk','ds','blk','pm','dm','cm','vio','oth'].forEach(id2=>$(id2).value=g[map[id2]||id2]??''); show('input')}
window.editGame=editGame; window.deleteGame=async id=>{if(currentUser&&confirm('削除しますか？'))await deleteDoc(doc(db,'games',id))};
function sum(gs){let s={q:0,twopa:0,twopm:0,threepa:0,threepm:0,fta:0,ftm:0,ast:0,or:0,dr:0,pk:0,ds:0,blk:0,pm:0,dm:0,cm:0,vio:0,oth:0}; gs.forEach(g=>Object.keys(s).forEach(k=>s[k]+=n(k==='q'?g.quarters:g[k]))); s.fga=s.twopa+s.threepa; s.fgm=s.twopm+s.threepm; s.reb=s.or+s.dr; s.stl=s.pk+s.ds; s.to=s.pm+s.dm+s.cm+s.vio+s.oth; s.g4=s.q/4||0; return s;}
function per(s,k){return s.g4?(s[k]/s.g4).toFixed(1):'0.0'}
function statCards(s,home=false){let rows=[['2P',`${per(s,'twopa')} / ${per(s,'twopm')}`,pct(s.twopm,s.twopa)],['3P',`${per(s,'threepa')} / ${per(s,'threepm')}`,pct(s.threepm,s.threepa)],['FG',`${per(s,'fga')} / ${per(s,'fgm')}`,pct(s.fgm,s.fga)],['FT',`${per(s,'fta')} / ${per(s,'ftm')}`,pct(s.ftm,s.fta)],['AST',per(s,'ast'),'4Q換算'],['REB',per(s,'reb'),'OR+DR'],['STL',per(s,'stl'),'PK+DS'],['BLK',per(s,'blk'),'4Q換算'],['TO',per(s,'to'),'合計']]; return rows.map(r=>`<div class="stat-card"><small>${r[0]}</small><strong>${r[1]}</strong><em>${r[2]}</em></div>`).join('')}
function renderAll(){fillPlayerSelects(); renderPlayers(); renderGames(); renderHome(); renderAnalysis(); renderVideos();}
function fillPlayerSelects(){['statPlayer','analysisPlayer'].forEach(id=>{let el=$(id), val=el.value||selectedPlayer; el.innerHTML='<option value="">選手を選択</option>'+players.map(p=>`<option value="${p.id}">#${p.no||''} ${p.name||''}</option>`).join(''); el.value=val;});}
function renderPlayers(){$('playerList').innerHTML=players.map(p=>`<div class="list-card"><div><b>#${p.no||''} ${p.name||''}</b><br><small>${p.pos||''} ${p.grade||''} ${p.height? p.height+'cm':''}</small></div></div>`).join('')||'<p>未登録</p>'}
function gameCard(g,edit=true){let r=n(g.myScore)>n(g.oppScore)?'○':n(g.myScore)<n(g.oppScore)?'●':'△'; return `<div class="match-card"><div><b>${g.date||''} vs ${g.opponent||''}</b><br><small>${g.tournament||''} / ${g.quarters||0}Q</small></div><div><div class="score">${g.myScore??'-'}-${g.oppScore??'-'} <span class="${r==='○'?'win':r==='●'?'lose':''}">${r}</span></div>${edit?`<button class="ghost" onclick="editGame('${g.id}')">修正</button> <button class="ghost" onclick="deleteGame('${g.id}')">削除</button>`:''}</div></div>`}
function renderGames(){let arr=[...games].sort((a,b)=>(b.date||'').localeCompare(a.date||'')); $('gameList').innerHTML=arr.map(g=>gameCard(g,true)).join('')||'<p>まだ試合がありません。ホームから入力してください。</p>'}
function renderHome(){let p=players.find(x=>x.id===selectedPlayer)||players[0]; if(!selectedPlayer&&p){selectedPlayer=p.id; localStorage.setItem('r32_selected_player',p.id)} $('homePlayerName').textContent=p?`#${p.no||''} ${p.name||''}`:'選手未選択'; $('homePlayerMeta').textContent=p?`${p.pos||''} ${p.grade||''} ${p.height? p.height+'cm':''}`:'分析画面で選手を選択してください'; let gs=games.filter(g=>g.playerId===selectedPlayer); $('homeDashboard').innerHTML=statCards(sum(gs),true); $('recentGames').innerHTML=gs.sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,5).map(g=>gameCard(g,false)).join('')||'<p>まだ試合がありません</p>'}
$('analysisPlayer').onchange=e=>{selectedPlayer=e.target.value; localStorage.setItem('r32_selected_player',selectedPlayer); buildTargets(); renderAnalysis(); renderHome();}; let scope='game'; qs('.segmented button').forEach(b=>b.onclick=()=>{qs('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');scope=b.dataset.scope;buildTargets();renderAnalysis()}); $('analysisTarget').onchange=renderAnalysis;
function keyOf(g,sc){if(sc==='game')return g.id;if(sc==='tournament')return g.tournament||'大会未設定';if(sc==='day')return g.date||'日付未設定';if(sc==='month')return (g.date||'').slice(0,7)||'月未設定';if(sc==='year')return (g.date||'').slice(0,4)||'年未設定'}
function buildTargets(){let gs=games.filter(g=>g.playerId===selectedPlayer); let keys=[...new Set(gs.map(g=>keyOf(g,scope)))].filter(Boolean); $('analysisTarget').innerHTML=keys.map(k=>`<option value="${k}">${scope==='game'?(gs.find(g=>g.id===k)?.opponent||k):k}</option>`).join('')}
function renderAnalysis(){if(!$('analysisTarget').options.length)buildTargets(); let target=$('analysisTarget').value; let gs=games.filter(g=>g.playerId===selectedPlayer && keyOf(g,scope)===target); $('analysisTitle').textContent=target||'対象を選択してください'; $('analysisSub').textContent=`${gs.length}試合 / ${sum(gs).q}Q / 4Q換算 ${(sum(gs).g4).toFixed(1)}試合`; $('targetMatches').innerHTML=(scope==='year'?'':gs.map(g=>gameCard(g,false)).join('')); $('analysisStats').innerHTML=statCards(sum(gs)); let s=sum(gs); $('analysisBreakdown').innerHTML=`<div class="breakdown"><b>STL内訳</b><p>PK ${s.pk} / DS ${s.ds}</p></div><div class="breakdown"><b>TO内訳</b><p>PM ${s.pm} / DM ${s.dm} / CM ${s.cm} / VIO ${s.vio} / OTH ${s.oth}</p></div>`}
$('saveVideoBtn').onclick=async()=>{if(!currentUser)return alert('ログインしてください'); await addDoc(collection(db,'videos'),{title:$('videoTitle').value,url:$('videoUrl').value,createdAt:serverTimestamp()});$('videoTitle').value=$('videoUrl').value=''}; function renderVideos(){$('videoList').innerHTML=videos.map(v=>`<a class="list-card" href="${v.url}" target="_blank"><b>${v.title||'Video'}</b><small>${v.url}</small></a>`).join('')||'<p>動画未登録</p>'}
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify({players,games,videos},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='r32-backup.json';a.click()};
if('serviceWorker'in navigator) navigator.serviceWorker.register('./service-worker.js');
