import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {planAssistMutation} from '../js/calculations/assist-play-calculations.js';
import {buildGameHistory,historyInsertionOverrides} from '../js/calculations/game-event-calculations.js';
const source=fs.readFileSync(new URL('../js/core/assist-play-store.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export async function','async function');
const players=[{id:'32',number:'32'},{id:'8',number:'8'}],game={id:'g',statsRegistrationType:'quarter',playEvents:[]};
const shot={id:'s',gameId:'g',playerId:'32',quarter:1,result:'made',shotValue:2,shotX:45,shotY:25,shotArea:'center_mid',shotType:'jump_shot',sequence:100,createdAt:100};
function harness(){const docs=new Map([['games/g',structuredClone(game)]]);let reads=0,writes=0;const c=vm.createContext({crypto,planAssistMutation,buildGameHistory,historyInsertionOverrides,db:{},doc:(_,collection,id)=>`${collection}/${id}`,serverTimestamp:()=>123,runTransaction:async(_,fn)=>{const staged=[];const result=await fn({get:async ref=>{reads++;return {id:ref.split('/')[1],exists:()=>docs.has(ref),data:()=>structuredClone(docs.get(ref))}},set:(ref,data)=>staged.push([ref,data])});for(const [ref,data] of staged){writes++;docs.set(ref,{...docs.get(ref),...structuredClone(data)})}return result}});vm.runInContext(source,c);return {docs,save:(action,revision)=>c.commitAssistMutation(game,[],players,{...action,historyClock:{clientId:'device',revision},historyStatIds:['g_32'],playId:'play',now:100}),reads:()=>reads,writes:()=>writes}}
test('create then edit survives callback retry and replay of older operation without extra snapshot reads',async()=>{const h=harness();await h.save({kind:'saveShot',shot},1);assert.equal(h.reads(),3,'same existing game + player stat transaction reads');await h.save({kind:'saveShot',shot:{...shot,result:'missed'},edit:true},2);const count=h.writes();await h.save({kind:'saveShot',shot},1);assert.equal(h.writes(),count);const q=h.docs.get('stats/g_32').quarters.q1;assert.equal(q.shots.length,1);assert.equal(q.shots[0].result,'missed');assert.equal(q.twoPm,0);assert.equal(q.twoPa,1);assert.equal(q.shots[0].shotX,45);assert.equal(q.shots[0].playId,'play')});
test('tombstone receipt prevents an old successful create from resurrecting a deleted shot',async()=>{const h=harness();await h.save({kind:'saveShot',shot},1);await h.save({kind:'delete',eventId:'shot:g_32:1:s'},2);await h.save({kind:'saveShot',shot},1);await h.save({kind:'delete',eventId:'shot:g_32:1:s'},2);assert.equal(h.docs.get('stats/g_32').quarters.q1.shots.length,0);assert.equal(h.docs.get('stats/g_32').quarters.q1.twoPa,0);assert.equal(h.docs.get('stats/g_32').historyClock.device,2)});
