import test from 'node:test';
import assert from 'node:assert/strict';
import {HistoryJournal,createHistoryOverlay} from '../js/core/history-journal.js';
import {planAssistMutation} from '../js/calculations/assist-play-calculations.js';
import {buildGameHistory,createPlayEvent} from '../js/calculations/game-event-calculations.js';
import {createShot} from '../js/calculations/shot-calculations.js';
const players=[{id:'32',number:'32'},{id:'8',number:'8'}];
const game={id:'g',statsRegistrationType:'quarter',quarters:4,playEvents:[],quarterParticipation:{q1:{starters:['32','8','a','b','c'],substitutions:[]}}};
const shot={...createShot({id:'s',gameId:'g',playerId:'32',quarter:1,shotArea:'center_mid',shotType:'jump_shot',result:'made',shotX:50,shotY:30,createdAt:100}),sequence:100};
function setup(){const journal=new HistoryJournal();journal.receive('games',[game]);return journal}
function current(j){return {game:j.project('games',[game])[0],stats:j.project('stats',[...j.documents].filter(([key])=>key.startsWith('stats/')).map(([,value])=>value))}}
function history(j){const s=current(j);return buildGameHistory(s.game,s.stats,players)}
function stage(j,action,revision){const before=current(j),after=planAssistMutation(before.game,before.stats,players,{playId:'play-s',assistId:'ast-s',now:100,...action}),stats=[...before.stats.filter(s=>!after.stats.some(n=>n.id===s.id)),...after.stats];const op={id:`op-${revision}`,createdAt:revision,historyClock:{clientId:'a',revision},overlay:createHistoryOverlay(before.game,before.stats,after.game,stats)};j.start(op);return {op,game:after.game,stats}}
function confirmed(result,revision){return {game:{...result.game,historyClock:{a:revision}},stats:result.stats.map(s=>({...s,historyClock:{a:revision}}))}}
test('SHOT survives empty/old stats listener, game-first acknowledgement and arbitrary delay',()=>{const j=setup(),r=stage(j,{kind:'saveShot',shot},1);assert.equal(history(j).length,1);j.receive('stats',[]);j.receive('games',[game]);assert.equal(history(j)[0].sourceId,'s');j.complete(r.op.id);const server=confirmed(r,1);j.receive('games',[server.game]);assert.equal(j.retire().length,0);assert.equal(history(j).length,1);j.receive('stats',server.stats);assert.equal(j.retire().length,1);assert.equal(history(j).length,1);assert.equal(current(j).stats[0].quarters.q1.shots[0].shotX,50)});
test('SHOT then REB retains both with equal sequence and another device snapshot',()=>{const j=setup(),s=stage(j,{kind:'saveShot',shot},1),before=current(j),reb=createPlayEvent({id:'reb',gameId:'g',quarter:1,player:players[0],statKey:'dr',sequence:101});const afterGame={...before.game,playEvents:[reb]},afterStats=structuredClone(before.stats);afterStats[0].quarters.q1.dr=1;j.start({id:'op-2',createdAt:2,historyClock:{clientId:'a',revision:2},overlay:createHistoryOverlay(before.game,before.stats,afterGame,afterStats)});const remote=createPlayEvent({id:'remote',gameId:'g',quarter:1,player:players[1],statKey:'ast',sequence:101});j.receive('games',[{...game,playEvents:[remote]}]);assert.deepEqual(history(j).map(e=>e.sourceId||e.id),['s','reb','remote']);assert.equal(current(j).stats[0].quarters.q1.quarter,1)});
test('pending edit wins over first transaction and stale snapshots without changing ID/playId/sequence',()=>{const j=setup(),first=stage(j,{kind:'saveShot',shot},1),edit=stage(j,{kind:'saveShot',shot:{...shot,result:'missed',sequence:900},edit:true},2),server=confirmed(first,1);j.receive('games',[server.game]);j.receive('stats',server.stats);j.complete(first.op.id);j.retire();assert.equal(history(j).length,1);assert.equal(history(j)[0].result,'missed');assert.equal(history(j)[0].sortValue,100);assert.equal(history(j)[0].playId,'play-s');const final=confirmed(edit,2);j.receive('games',[final.game]);j.receive('stats',final.stats);j.complete(edit.op.id);j.retire();j.receive('stats',server.stats);assert.equal(history(j)[0].result,'missed')});
test('pending deletion remains absent when the create resolves; no resurrection on replay',()=>{const j=setup(),first=stage(j,{kind:'saveShot',shot},1),eventId=history(j)[0].eventId,deleted=stage(j,{kind:'delete',eventId},2),server=confirmed(first,1);assert.equal(history(j).length,0);j.receive('games',[server.game]);j.receive('stats',server.stats);assert.equal(history(j).length,0);const final=confirmed(deleted,2);j.receive('stats',final.stats);j.receive('games',[final.game]);j.complete(first.op.id);j.complete(deleted.op.id);j.retire();j.receive('stats',server.stats);assert.equal(history(j).length,0)});
test('offline journal reload restores edited SHOT exactly once then releases acknowledged payloads',()=>{const j=setup();stage(j,{kind:'saveShot',shot},1);const edited=stage(j,{kind:'saveShot',shot:{...shot,result:'missed'},edit:true},2);const reboot=setup();for(const op of structuredClone([...j.operations.values()]))reboot.start(op);assert.equal(history(reboot).length,1);assert.equal(history(reboot)[0].result,'missed');const server=confirmed(edited,2);reboot.receive('stats',server.stats);reboot.receive('games',[server.game]);for(const id of reboot.operations.keys())reboot.complete(id);assert.equal(reboot.retire().length,2);assert.equal(history(reboot).length,1)});
test('pending Made SHOT supports AST links and metadata survives both listener orders',()=>{const j=setup(),first=stage(j,{kind:'saveShot',shot},1),linked=stage(j,{kind:'link',shotEventId:history(j)[0].eventId,assistPlayerId:'8'},2);const server=confirmed(first,1);j.receive('stats',server.stats);const h=history(j),sh=h.find(e=>e.type==='shot'),ast=h.find(e=>e.statKey==='ast');assert.equal(sh.assistEventId,ast.eventId);assert.equal(sh.playId,ast.playId);assert.equal(ast.shotEventId,sh.eventId);assert.equal(current(j).stats.find(s=>s.playerId==='32').quarters.q1.shots[0].shotType,shot.shotType)});
test('remote same-player counter increments survive pending overlay',()=>{const j=setup();const before=current(j),event=createPlayEvent({id:'reb',gameId:'g',quarter:1,player:players[0],statKey:'dr',sequence:101}),stat={id:'g_32',gameId:'g',playerId:'32',quarters:{q1:{dr:1,quarter:1,registered:true}}};j.start({id:'op',createdAt:1,historyClock:{clientId:'a',revision:1},overlay:createHistoryOverlay(before.game,[],{...game,playEvents:[event]},[stat])});j.receive('stats',[{...stat,quarters:{q1:{dr:3,quarter:1,registered:true}}}]);assert.equal(current(j).stats[0].quarters.q1.dr,4);assert.equal(current(j).stats[0].quarters.q1.quarter,1)});
