import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createStatsBaseline,LOAD_ERROR,CONFLICT_ERROR} from '../js/core/normal-stats-guard.js';
const app=fs.readFileSync(new URL('../js/app.js',import.meta.url),'utf8');
const start=app.indexOf('function statsForm('),source=app.slice(start,app.indexOf('\nasync function import2026ShigaMen',start));
// A small DOM test double drives the actual form function and async handlers.
// Store/transaction behavior is separately tested with the real mutation planner.
function form(){
 const nodes=new Map(),pending=[];let writes=0,message='',connected=true;
 const parse=html=>{for(const m of html.matchAll(/<[^>]+\bid="([^"]+)"[^>]*>/g)){const e=element(m[1]);e.value=m[0].match(/value="([^"]*)"/)?.[1]||'';e.disabled=/\sdisabled(?:\s|>)/.test(m[0]);nodes.set(m[1],e)}if(nodes.has('sfPlayer'))nodes.get('sfPlayer').value='p'};
 function element(id=''){return {id,value:'',disabled:false,classList:{add(){},toggle(){}},get isConnected(){return connected},set innerHTML(v){this.html=v;parse(v)},get innerHTML(){return this.html},set textContent(v){this.text=v},get textContent(){return this.text},querySelector(selector){return this.children?.[selector]||(this.children??={},this.children[selector]=element())},prepend(){}}}
 const game={id:'g',statsRegistrationType:'quarter',quarters:4,registrationDefaultsVersion:1},stat={id:'g_p',gameId:'g',playerId:'p',quarters:{q1:{registered:true,quarter:1,dr:3}}};
 const c=vm.createContext({matchMedia:()=>({matches:false}),console,window:{},document:{querySelector:s=>s.startsWith('#')?nodes.get(s.slice(1)):null,querySelectorAll:()=>[],createElement:()=>element()},$:s=>nodes.get(s.slice(1)),state:{games:[game],stats:[],players:[{id:'p'}],lastPlayerId:'p'},STAT_KEYS:['twoPa','twoPm','threePa','threePm','fta','ftm','ast','blk','passCut','dribbleCut','stealOther','or','dr','passMiss','dribbleMiss','catchMiss','violation','otherTo','pf','fouled'],LOAD_ERROR,CONFLICT_ERROR,requireLogin:()=>true,num:v=>Number(v)||0,escapeHtml:String,getGameStatsRegistrationType:()=> 'quarter',hasShotPointData:()=>false,detailStatsView:()=> 'q1',participationRequired:()=>false,quarterParticipation:()=>({}),participationPlayerLabel:()=> 'test',latestHistoryHtml:()=>'',modal:parse,setLastPlayerId(){},bindLatestHistory(){},numInput:(id,v)=>`<input id="${id}" value="${Number(v)||0}">`,receivedFoulTotal:s=>s.fouled||0,registeredQuarterNumbers:()=>[1],quarterKey:q=>'q'+q,bindNumberSteppers(){},setupStatsDirty(){},loadNormalStats:(g,p,q)=>new Promise((resolve,reject)=>pending.push({resolve:()=>resolve({stat:structuredClone(stat),baseline:createStatsBaseline(game,stat,p,q)}),reject})),toast:s=>message=s,closeModal:()=>connected=false,serverTimestamp:()=>0,effectiveSeasonId:()=> 's',shotReceivedFoulCount:()=>0,participationPlayer:()=>({id:'p'}),reconcileStatEvents:()=>({}),saveStatsAndReturnToTop:async({save,onFailure})=>{try{await save();return true}catch(e){onFailure(e);return false}},saveAssistPlay:async(g,a)=>{writes++;stat.quarters.q1.dr=a.values.dr},requestAnimationFrame:f=>f(),projectLocalHistory(){}});
 vm.runInContext(source,c);c.statsForm('g',1);
 return {nodes,pending,stat,writes:()=>writes,message:()=>message,flush:()=>new Promise(r=>setImmediate(r)),close:()=>connected=false};
}
test('⑤⑥ actual form disables save and handler rejects uninitialized zero',async()=>{const h=form();assert.equal(h.nodes.get('saveStats').disabled,true);await h.nodes.get('saveStats').onclick();assert.equal(h.writes(),0);assert.equal(h.message(),LOAD_ERROR);assert.equal(h.nodes.has('dr'),false)});
test('③④ actual form renders server 3, permits explicit 0 and reloads baseline after save',async()=>{const h=form();h.pending[0].resolve();await h.flush();assert.equal(h.nodes.get('dr').value,'3');assert.equal(h.nodes.get('saveStats').disabled,false);h.nodes.get('dr').value='0';const saving=h.nodes.get('saveStats').onclick();await h.flush();assert.equal(h.stat.quarters.q1.dr,0);assert.equal(h.writes(),1);assert.equal(h.nodes.get('saveStats').disabled,true);h.pending[1].resolve();await saving;assert.equal(h.nodes.get('dr').value,'0');assert.equal(h.nodes.get('saveStats').disabled,false)});
test('⑨ actual read failure remains disabled and writes nothing',async()=>{const h=form();h.pending[0].reject(Error('failed'));await h.flush();assert.equal(h.nodes.get('saveStats').disabled,true);await h.nodes.get('saveStats').onclick();assert.equal(h.writes(),0)});
test('out-of-order load responses cannot enable wrong form',async()=>{const h=form();h.nodes.get('sfPlayer').onchange();h.pending[1].reject(Error('latest failed'));await h.flush();h.pending[0].resolve();await h.flush();assert.equal(h.nodes.get('saveStats').disabled,true);assert.equal(h.nodes.has('dr'),false)});
