import {sessionScope} from '../js/core/quarter-session-model.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createOfflineOperation,sortOfflineOperations,isRetryableNetworkError} from '../js/core/offline-operation-queue.js';
const code=fs.readFileSync(new URL('../js/core/offline-sync.js',import.meta.url),'utf8').replace(/^import [\s\S]*? from .*;\r?\n/gm,'').replaceAll('export async function','async function').replaceAll('export function','function').replace(/^export \{.*\};/gm,'');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
async function harness({online=true,fail=false}={}){const rows=new Map(),calls=[],notices=[],events=new EventTarget(),gates=[];let hold=true;events.addEventListener('r32-offline-operation-change',event=>notices.push(event.detail));
 const context=vm.createContext({crypto,console,CustomEvent,Date,sessionScope,enqueueSessionOperation:async op=>{Object.assign(op,{sessionVersion:1,syncState:'draft',operationId:op.id,createdAt:rows.size+1});rows.set(op.id,structuredClone(op));return op},markQuarterReady:async(g,q)=>{for(const op of rows.values())if(op.gameId===g&&op.quarter===q&&op.syncState==='draft')op.syncState='ready'},commitQuarterOperation:async op=>{calls.push(op.payload.action.kind);if(hold)await new Promise(resolve=>gates.push(resolve));if(fail)throw Object.assign(Error('denied'),{code:'permission-denied'});return {}},navigator:{onLine:online},setTimeout,createOfflineOperation,sortOfflineOperations,isRetryableNetworkError,addEventListener:events.addEventListener.bind(events),dispatchEvent:events.dispatchEvent.bind(events),enqueueOfflineOperation:async op=>rows.set(op.id,structuredClone(op)),listOfflineOperations:async()=>sortOfflineOperations([...rows.values()]),offlineOperationCount:async()=>rows.size,updateOfflineOperation:async op=>rows.set(op.id,structuredClone(op)),removeOfflineOperation:async id=>rows.delete(id),commitAssistMutation:async(g,s,p,a)=>{calls.push(a.kind);if(hold)await new Promise(resolve=>gates.push(resolve));if(fail)throw Object.assign(Error('denied'),{code:'permission-denied'});return {}},db:{},doc:()=>{},setDoc:async()=>{},serverTimestamp:()=>{}});
 vm.runInContext(code,context);await context.initializeOfflineSync({uid:'owner'});
 const submit=kind=>context.submitOfflineCapable('assist',{game:{id:'g'},stats:[],players:[],action:{kind}},()=>{throw Error('online bypass forbidden')},{overlay:{documents:[{key:'games/g',before:{id:'g'},patch:null}]}});
 return {context,rows,calls,notices,submit,release:()=>{hold=false;for(const resolve of gates)resolve()},tick};
}
test('durable online create returns before server; edit and delete cannot overtake it',async()=>{const h=await harness();await h.submit('saveShot');await tick();assert.deepEqual(h.calls,[]);await h.submit('edit');await h.submit('delete');assert.deepEqual(h.calls,[]);assert.equal(h.rows.size,3);h.release();await h.context.confirmQuarterSession('g',1);for(let i=0;i<10;i++)await tick();assert.deepEqual(h.calls,['saveShot','edit','delete']);assert.ok([...h.rows.values()].every(op=>op.committed));assert.equal(new Set(h.notices.filter(x=>x.action==='completed').map(x=>x.operationId)).size,3)});
test('offline create and edit persist and replay in order once online',async()=>{const h=await harness({online:false});await h.submit('saveShot');await h.submit('edit');assert.equal(h.calls.length,0);h.context.navigator.onLine=true;h.release();await h.context.synchronizeOfflineOperations();assert.deepEqual(h.calls,[]);await h.context.confirmQuarterSession('g',1);assert.deepEqual(h.calls,['saveShot','edit']);await h.context.synchronizeOfflineOperations();assert.deepEqual(h.calls,['saveShot','edit'])});
test('failed predecessor remains durable and blocks dependent deletion',async()=>{const h=await harness({online:false,fail:true});await h.submit('saveShot');await h.submit('delete');h.context.navigator.onLine=true;h.release();await assert.rejects(h.context.confirmQuarterSession('g',1));assert.deepEqual(h.calls,['saveShot']);assert.equal(h.rows.size,2);assert.equal([...h.rows.values()][0].attempts,1)});
