import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const app = readFileSync(new URL("../js/app.js", import.meta.url), "utf8");
const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const participationCss = readFileSync(new URL("../styles/participation.css", import.meta.url), "utf8");
for (const marker of ["participationMode:'required'", "quarterDurationMinutes:durationMinutes", "Q開始メンバーを5人設定してください", "statsPlayerOut", "stats-player-out-button", "＋ 未登録選手を追加", "前Q終了メンバーをコピー", "sortSubstitutions(substitutions)"]) assert.ok(app.includes(marker), marker);
assert.ok(app.includes("participationRequired(g)&&mode==='quarter'"));
assert.ok(index.includes("participation.css?v=20260824-compact-sub-time-v3"));
assert.ok(index.includes("app.js?v=20260830-history-insert-ft-v2"));
assert.ok(index.includes("min-display.css?v=20260822-foul-stats-v2"));
assert.ok(app.includes("averagePlayerPlayingTime(gamesWithStats(targetGames(),p.id),p.id)"));
assert.ok(app.includes("selectedGamePlayingTime(game,p.id)"));
assert.ok(app.includes("MIN ${value.registered?formatClock(value.seconds):'--:--'}"));
assert.ok(app.includes("const showSeasonSwitcher=state.tab!=='gameDetail'"));
assert.ok(app.includes("openParticipationFromGameForm"));
assert.ok(!app.includes("function participationAction"));
assert.ok(!app.includes('class="card current-lineup"'));
assert.ok(!app.includes('stats-player-out-action'));
assert.match(app, /id="saveStats">保存<\/button><button class="btn ghost" id="closeModal">閉じる<\/button>.*id="statsPlayerOut">OUT<\/button>/s);
assert.ok(app.includes("filter(id=>!onCourt.includes(id))"));
assert.ok(app.includes('id="subTime"'));
assert.ok(app.includes("例：6分15秒は 615"));
assert.ok(app.includes("parseCompactRemainingTime($('#subTime').value,duration)"));
assert.ok(app.includes("timeInput.onfocus=placeTimeCaretAtEnd"));
assert.ok(app.includes("timeInput.setSelectionRange(end,end)"));
assert.ok(!app.includes('id="subMinutes"'));
assert.ok(!app.includes('id="subSeconds"'));
assert.match(participationCss, /\.participation-sub-form input,\.participation-sub-form select\{font-size:16px\}/);
console.log("participation UI contract: ok");
