import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const app = readFileSync(new URL("../js/app.js", import.meta.url), "utf8");
const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
for (const marker of ["participationMode:'required'", "quarterDurationMinutes:durationMinutes", "Q開始メンバーを5人設定してください", "data-player-out", "＋ 未登録選手を追加", "前Q終了メンバーをコピー", "sortSubstitutions(substitutions)"]) assert.ok(app.includes(marker), marker);
assert.ok(app.includes("participationRequired(g)&&mode==='quarter'"));
assert.ok(index.includes("participation.css?v=20260821-1"));
assert.ok(index.includes("app.js?v=20260821-analysis-info-layout-v1"));
assert.ok(index.includes("min-display.css?v=20260821-2"));
assert.ok(app.includes("averagePlayerPlayingTime(gamesWithStats(targetGames(),p.id),p.id)"));
assert.ok(app.includes("selectedGamePlayingTime(game,p.id)"));
assert.ok(app.includes("MIN ${value.registered?formatClock(value.seconds):'--:--'}"));
assert.ok(app.includes("const showSeasonSwitcher=state.tab!=='gameDetail'"));
assert.ok(app.includes("openParticipationFromGameForm"));
assert.ok(!app.includes("function participationAction"));
console.log("participation UI contract: ok");
