import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../js/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../styles/quick-input.css',import.meta.url),'utf8');
const viewportScript=fs.readFileSync(new URL('../js/ui/mobile-modal-viewport-fit.js',import.meta.url),'utf8');
const viewportCss=fs.readFileSync(new URL('../styles/mobile-modal-viewport-fit.css',import.meta.url),'utf8');
for(const marker of ['function quickStatsForm','function quickPlayerSheet','function quickShotRegistration','function saveQuickStats','1つ戻す','通常入力','data-quick-action="reb"','data-quick-action="fouled"'])assert.ok(app.includes(marker),marker);
for(const marker of ['<h2>選手を選択</h2>','function quickActionSheet','quick-selected-player','id="quickChangePlayer"','data-quick-action="out"'])assert.ok(app.includes(marker),marker);
for(const key of ['passCut','dribbleCut','stealOther','passMiss','dribbleMiss','catchMiss','violation','otherTo'])assert.ok(app.includes(`key:'${key}'`),key);
assert.match(app,/currentPlayersAt\(game,quarter,remainingSeconds\)/);
assert.match(app,/if\(saving\)return/);
assert.match(app,/data-quick-close/);
assert.match(app,/addEventListener\('pointerup',close\)/);
assert.doesNotMatch(app,/class="quick-close" id="closeModal"/);
assert.match(app,/remainingSeconds:''/);
assert.match(app,/return \{remainingSeconds:hasTime\?saved\.remainingSeconds:'',undo:/);
assert.match(app,/remainingSeconds===''\?validateQuarterParticipation/);
assert.match(app,/remainingSeconds===''\?\{\}:\{remainingSeconds\}/);
assert.match(app,/quickSetSession\(game,quarter,\{remainingSeconds,undo:/);
assert.match(app,/function quickShotRegistration[\s\S]*?<h2>シュート位置を選択<\/h2>/);
assert.match(viewportScript,/SHOT_POSITION_TITLE = 'シュート位置を選択'/);
assert.match(viewportCss,/\.shot-entry-viewport \.shot-type-grid \{[\s\S]*?grid-template-columns: repeat\(3/);
assert.match(css,/env\(safe-area-inset-bottom\)/);
assert.match(css,/font-size:18px!important/);
assert.match(css,/\.quick-head-close/);
assert.match(app,/quick-input\.css\?v=20260829-quick-close-v2/);
console.log('quick input contract: ok');
