import assert from 'node:assert/strict';
import { OPPONENT_RANKS, calculateSeasonRanks, calculateSeasonalTeamRank, calculateTeamPower, calculatePrefectureStrengthBonuses, placementLabelToRank, rankToScore } from '../js/calculations/opponent-team-calculations.js';
const p=(season,label,extra={})=>({season,placementLabel:label,tournamentLevel:'prefecture',...extra});
assert.deepEqual(OPPONENT_RANKS,['E','D','C','B','A','A+','S']);
assert.deepEqual(['E','D','C','B','A','A+','S'].map(rankToScore),[1,2,3,4,5,6,7]);
assert.equal(placementLabelToRank('優勝'),'S');
assert.equal(placementLabelToRank('準優勝'),'A+');
assert.equal(placementLabelToRank('ベスト4'),'A');
assert.equal(placementLabelToRank('ベスト8'),'B');
assert.equal(placementLabelToRank('ベスト16'),'C');
assert.equal(placementLabelToRank('ベスト32'),'D');
assert.equal(placementLabelToRank('ベスト64以下・県大会出場'),'E');
assert.equal(placementLabelToRank('初戦敗退'),null);
assert.equal(placementLabelToRank('1回戦敗退'),null);
const highest=calculateSeasonRanks([p('2026-27','ベスト8'),p('2026-27','準優勝')])['2026-27'];
assert.equal(highest.rank,'A+');
assert.equal(highest.calculationMethod,'highest-prefecture-placement');
assert.equal(calculateSeasonalTeamRank([p('2026-27','ベスト8'),p('2025-26','優勝')],{currentSeason:'2026-27'}).rank,'B');
assert.equal(calculateSeasonalTeamRank([p('2025-26','優勝')],{currentSeason:'2026-27'}).overallRankStatus,'provisional');
const placements=[p('2026-27','ベスト8'),{season:'2026-27',tournamentLevel:'block',placementLabel:'ベスト4'}];
assert.deepEqual(calculateTeamPower(placements,{season:'2026-27',prefectureStrengthBonus:30}),{rank:'B',basePower:400,prefectureStrengthBonus:30,prefectureStrengthIndex:130,blockBonus:80,nationalBonus:0,power:510});
const strengths=calculatePrefectureStrengthBonuses([{prefecture:'兵庫県',tournamentPlacements:[{season:'2026-27',tournamentLevel:'block',placementLabel:'ベスト8'}]}],{season:'2026-27'});
assert.equal(strengths['兵庫県'].bonus,24);
console.log('season team ranks and Team Power: ok');
