import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const app = readFileSync(new URL("../js/app.js", import.meta.url), "utf8");
const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const calculations = readFileSync(new URL("../js/calculations/shot-calculations.js", import.meta.url), "utf8");
const css = readFileSync(new URL("../styles/shot-registration.css", import.meta.url), "utf8");
const detailCss = readFileSync(new URL("../styles/detail-stats-actions.css", import.meta.url), "utf8");
const teamAnalysis = readFileSync(new URL("../js/ui/team-shot-analysis.js", import.meta.url), "utf8");
const selectedAreaHighlight = readFileSync(new URL("../js/ui/shot-selected-area-highlight.js", import.meta.url), "utf8");

assert.match(app, /selectedShotId=normalizedEditing\?\.id\|\|''/);
assert.match(app, /function shotTypeButtonLabel\(id\)\{return id==='running_shot'\?'ランニング\/<br>ステップイン':escapeHtml\(SHOT_TYPES\[id\]\|\|''\)\}/);
assert.match(app, /data-shot-type="\$\{id\}">\$\{shotTypeButtonLabel\(id\)\}<\/button>/);
assert.match(app, /data-legacy-type="\$\{id\}">\$\{shotTypeButtonLabel\(id\)\}<\/button>/);
assert.match(app, /selectedTypes=new Set\(\)/);
assert.match(app, /data-analysis-shot-type="\$\{id\}"><span>\$\{shotTypeButtonLabel\(id\)\}<\/span>/);
assert.match(app, /function lockModalBackground\(\)/);
assert.match(app, /document\.body\.style\.top=`-\$\{modalBackgroundScrollY\}px`/);
assert.match(app, /function unlockModalBackground\(\)/);
assert.match(app, /window\.scrollTo\(0,modalBackgroundScrollY\)/);
assert.match(app, /data-select-shot=/);
assert.match(app, /shot-selection-ring/);
assert.match(app, /shot-foul-ring/);
assert.match(app, /event\.stopPropagation\(\)/);
assert.match(app, /id="shotWasFouled"/);
assert.match(app, /function renderKeepingModalScroll\(render\)/);
assert.match(app, /nextCard\.scrollTop=scrollTop/);
assert.match(app, /renderKeepingModalScroll\(redrawCourt\)/);
assert.doesNotMatch(app, /data-shot-filter-foul/);
assert.match(app, /\['made','Made'\],\['missed','Miss'\]/);
assert.match(app, /data-analysis-fouled/);
assert.doesNotMatch(app, /analysis-points-tappable/);
assert.match(app, /court-analysis-button/);
assert.match(app, />コート分析</);
assert.doesNotMatch(app, /analysis-shot-filter-details/);
assert.match(app, /data-analysis-area-shortcut/);
assert.match(app, /data-analysis-result/);
assert.match(app, /data-analysis-type/);
assert.doesNotMatch(app, /analysisActiveFilters/);
assert.match(app, /filterShotsBySelections/);
assert.doesNotMatch(app, /analysisShotTotal/);
assert.match(app, /selectedTypes/);
assert.match(app, /shot-analysis-conditions/);
assert.doesNotMatch(app, /resetTemporaryAnalysis/);
assert.match(app, /viewBox="0 0 100 108"/);
assert.doesNotMatch(app, /court-zone-guides/);
assert.match(app, /バックコート3P/);
assert.doesNotMatch(app, /data-shot-area="long_range_3p"/);
assert.match(app, /<th>No\.<\/th>/);
assert.match(app, /<div class="section-title">シュート明細<\/div>/);
assert.doesNotMatch(app, /id="shotQuarter"/);
assert.match(app, /data-shot-result="made" disabled>Made/);
assert.match(app, /data-shot-result="missed" disabled>Miss/);
assert.match(app, /button\.disabled=!\(shotX!=null&&shotY!=null&&areaId&&typeId\)/);
assert.match(app, /row\.onclick=\(\)=>onMark\?\./);
assert.match(app, /await saveAssistPlay\(game,\{kind:'saveShot',shot,edit:Boolean\(editingShot\)\},quarter\|\|1\);statsForm\(gameId,quarter\)/);
assert.match(css, /\.shot-list-row\.selected/);
assert.match(css, /html\.modal-open,body\.modal-open \{ overflow:hidden; overscroll-behavior:none; \}/);
assert.match(css, /body\.modal-open \{ position:fixed;/);
assert.match(css, /\.modal \.card \{ overscroll-behavior:contain; -webkit-overflow-scrolling:touch; touch-action:pan-y; \}/);
assert.match(css, /\.shot-foul-ring/);
assert.match(css, /\.shot-selection-ring/);
assert.doesNotMatch(css, /\.court-zone-guides/);
assert.match(selectedAreaHighlight, /const STEP = 0\.25;/);
assert.match(selectedAreaHighlight, /const areaPathCache = new Map\(\);/);
assert.match(selectedAreaHighlight, /let runStart = null;/);
assert.match(selectedAreaHighlight, /areaPathCache\.set\(areaId, d\);/);
assert.doesNotMatch(css, /shot-selection-pulse/);
assert.doesNotMatch(css, /running_shot[\s\S]{0,160}::before/);
assert.doesNotMatch(css, /running_shot[\s\S]{0,160}font-size\s*:\s*0/);
assert.doesNotMatch(index, /running_shot[\s\S]{0,200}::before/);
assert.doesNotMatch(index, /running_shot[\s\S]{0,200}font-size\s*:\s*0/);
assert.match(index, /js\/app\.js\?v=20260902-history-safety-v1/);
assert.doesNotMatch(index, /shot-analysis-area-tags\.js/);
assert.doesNotMatch(index, /analysis-shot-area-player-controls\.js/);
assert.doesNotMatch(index, /shot-analysis-legacy-filter-fix\.js/);
assert.equal(existsSync(new URL("../js/ui/shot-analysis-area-tags.js", import.meta.url)), false);
assert.equal(existsSync(new URL("../js/ui/analysis-shot-area-player-controls.js", import.meta.url)), false);
assert.equal(existsSync(new URL("../js/ui/shot-analysis-legacy-filter-fix.js", import.meta.url)), false);
assert.match(app, /const selectedAreas=new Set\(SHOT_AREA_ORDER\)/);
assert.match(app, /selectedAreas\.has\(areaId\)\?selectedAreas\.delete\(areaId\):selectedAreas\.add\(areaId\)/);
assert.match(app, /shotCourtSvg\(shots,null,'',\[\.\.\.selectedAreas\]\)/);
assert.match(app, /id="analysisSelectAll"/);
assert.match(app, /id="analysisClearAll"/);
assert.match(app, /analysisSelectAll'\)\.onclick=\(\)=>\{SHOT_AREA_ORDER\.forEach\(id=>selectedAreas\.add\(id\)\);renderAnalysis\(\)\}/);
assert.match(app, /analysisClearAll'\)\.onclick=\(\)=>\{selectedAreas\.clear\(\);renderAnalysis\(\)\}/);
assert.match(app, /試投数/);
assert.match(app, /成功数/);
assert.match(app, /analysis-player-condition/);
assert.match(app, /sortPlayersByCategoryAndNumber\(state\.players\)/);
assert.match(app, /state\.lastPlayerId=nextId;setLastPlayerId\(nextId\)/);
assert.doesNotMatch(app, /MutationObserver/);
assert.match(css, /\.analysis-area-overlay/);
assert.match(css, /\.court-filter-chip\.active/);
assert.match(css, /\.analysis-player-menu\[hidden\]/);
assert.match(css, /\.shot-analysis-tag-panel/);
assert.match(css, /\.analysis-shot-heading/);
assert.match(css, /\.shot-analysis-quick-filters/);
assert.match(css, /\.shot-analysis-filter-row/);
assert.match(css, /\.shot-analysis-quick-filters \.btn:disabled/);
assert.doesNotMatch(css, /\.shot-analysis-active-filters/);
assert.doesNotMatch(css, /\.analysis-points-tappable/);
assert.match(detailCss, /\.detail-stat-view-seg \.detail-stat-view-btn\.unsaved\.active/);
assert.doesNotMatch(detailCss, /\.detail-stat-view-seg \.detail-stat-view-btn\.active \{/);
assert.match(detailCss, /border: 2px solid #ffffff/);
assert.match(css, /\.btn\[aria-pressed="true"\]/);
assert.match(calculations, /running_shot: "ランニングシュート"/);
assert.match(calculations, /shot\.shotType === "under_basket" \? "jump_shot"/);
assert.match(calculations, /if \(areaId === "backcourt_3p"\) return \["jump_shot", "buzzer_beater"\]/);
assert.match(calculations, /if \(group === "three"\) return \["jump_shot", "running_shot"\]/);
assert.match(calculations, /if \(group === "mid"\) return \["jump_shot", "running_shot", "floater"\]/);
assert.match(calculations, /if \(group === "inside" \|\| group === "under"\) return \["jump_shot", "running_shot", "layup", "floater", "tap"\]/);
assert.match(index, /team-shot-analysis\.js\?v=20260818-buzzer-filter-v1/);
assert.match(app, /M41\.333 10\.5A8\.667 8\.667/);
assert.match(teamAnalysis, /M41\.333 10\.5A8\.667 8\.667/);
assert.doesNotMatch(app, /M36 10\.5A14 14/);
assert.doesNotMatch(teamAnalysis, /M36 10\.5A14 14/);
assert.match(calculations, /SHOT_AREA_MODEL_VERSION = "fiba-2024-r32-v3-inner-no-charge"/);
assert.doesNotMatch(index, /team-shot-analysis-filter-active-fix\.js/);
assert.equal(existsSync(new URL("../js/ui/team-shot-analysis-filter-active-fix.js", import.meta.url)), false);
assert.match(teamAnalysis, /const selectedAreas = new Set\(\)/);
assert.match(teamAnalysis, /selectedAreas\.has\(shotAreaForRecord\(shot\)\)/);
assert.match(teamAnalysis, /if \(selectedAreas\.has\(areaId\)\) selectedAreas\.delete\(areaId\)/);
assert.match(teamAnalysis, /distance = 'all';\s*side = 'all';\s*selectedType = ''/);
assert.match(teamAnalysis, /selectedAreas\.clear\(\);\s*selectedType = ''/);
assert.match(teamAnalysis, /shotCourtSvg\(displayShots, visibleAreas\)/);
assert.match(teamAnalysis, /team-analysis-area-overlay/);
assert.match(teamAnalysis, /data-team-area-rows/);
assert.match(teamAnalysis, /data-team-type-detail/);
assert.match(teamAnalysis, /if \(button\.disabled\) return/);
assert.doesNotMatch(teamAnalysis, /analysis-player-condition/);

console.log("shot UI contract: ok");
