import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync(new URL("../js/app.js", import.meta.url), "utf8");
const calculations = readFileSync(new URL("../js/calculations/shot-calculations.js", import.meta.url), "utf8");
const css = readFileSync(new URL("../styles/shot-registration.css", import.meta.url), "utf8");
const detailCss = readFileSync(new URL("../styles/detail-stats-actions.css", import.meta.url), "utf8");

assert.match(app, /selectedShotId=normalizedEditing\?\.id\|\|''/);
assert.match(app, /function shotTypeButtonLabel\(id\)\{return id==='running_shot'\?'ランニング\/<br>ステップイン':escapeHtml\(SHOT_TYPES\[id\]\|\|''\)\}/);
assert.match(app, /data-shot-type="\$\{id\}">\$\{shotTypeButtonLabel\(id\)\}<\/button>/);
assert.match(app, /data-legacy-type="\$\{id\}">\$\{shotTypeButtonLabel\(id\)\}<\/button>/);
assert.match(app, /typeFilters=SHOT_TYPE_ORDER\.map\(id=>\['type',id,shotTypeButtonLabel\(id\)\]\)/);
assert.match(app, /data-analysis-shot-type="\$\{id\}"><span>\$\{shotTypeButtonLabel\(id\)\}<\/span>/);
assert.match(app, /function lockModalBackground\(\)/);
assert.match(app, /document\.body\.style\.top=`-\$\{modalBackgroundScrollY\}px`/);
assert.match(app, /function unlockModalBackground\(\)/);
assert.match(app, /window\.scrollTo\(0,modalBackgroundScrollY\)/);
assert.match(app, /data-select-shot=/);
assert.match(app, /shot-selection-ring/);
assert.match(app, /shot-foul-ring/);
assert.match(app, /event\.stopPropagation\(\)/);
assert.match(app, /id="shotWasFouled"/);
assert.doesNotMatch(app, /data-shot-filter-foul/);
assert.match(app, /\['foul','yes','ファウル'\]/);
assert.match(app, /\['result','made','Made'\]/);
assert.match(app, /\['result','missed','Miss'\]/);
assert.doesNotMatch(app, /analysis-points-tappable/);
assert.match(app, /court-analysis-button/);
assert.match(app, />コート分析</);
assert.doesNotMatch(app, /analysis-shot-filter-details/);
assert.match(app, /data-shot-analysis-filter/);
assert.match(app, /analysisQuickFilters/);
assert.match(app, /shot-analysis-filter-row primary/);
assert.match(app, /shot-analysis-filter-row types/);
assert.match(app, /canSelect=\(field,value\)=>/);
assert.match(app, /if\(button\.disabled\)return/);
assert.doesNotMatch(app, /analysisActiveFilters/);
assert.match(app, /filters\[field\]=filters\[field\]===value\?'':value/);
assert.doesNotMatch(app, /analysisShotTotal/);
assert.match(app, /data-analysis-shot-type/);
assert.match(app, /selectedType/);
assert.match(app, /shot-analysis-conditions/);
assert.match(app, /displayShots=selectedType/);
assert.match(app, /viewBox="0 0 100 108"/);
assert.match(app, /バックコート3P/);
assert.doesNotMatch(app, /data-shot-area="long_range_3p"/);
assert.match(app, /<th>No\.<\/th>/);
assert.match(app, /<div class="section-title">シュート明細<\/div>/);
assert.doesNotMatch(app, /id="shotQuarter"/);
assert.match(app, /data-shot-result="made" disabled>Made/);
assert.match(app, /data-shot-result="missed" disabled>Miss/);
assert.match(app, /button\.disabled=!\(shotX!=null&&shotY!=null&&areaId&&typeId\)/);
assert.match(app, /row\.onclick=\(\)=>onMark\?\./);
assert.match(app, /await persistShotCollections\(gameId,playerId,collections\);statsForm\(gameId,quarter\)/);
assert.match(css, /\.shot-list-row\.selected/);
assert.match(css, /html\.modal-open,body\.modal-open \{ overflow:hidden; overscroll-behavior:none; \}/);
assert.match(css, /body\.modal-open \{ position:fixed;/);
assert.match(css, /\.modal \.card \{ overscroll-behavior:contain; -webkit-overflow-scrolling:touch; touch-action:pan-y; \}/);
assert.match(css, /\.shot-foul-ring/);
assert.match(css, /\.shot-selection-ring/);
assert.doesNotMatch(css, /shot-selection-pulse/);
assert.doesNotMatch(css, /running_shot[\s\S]{0,160}::before/);
assert.doesNotMatch(css, /running_shot[\s\S]{0,160}font-size\s*:\s*0/);
assert.match(css, /\.analysis-shot-heading/);
assert.match(css, /\.shot-analysis-quick-filters/);
assert.match(css, /\.shot-analysis-filter-row/);
assert.match(css, /\.shot-analysis-quick-filters \.btn:disabled/);
assert.doesNotMatch(css, /\.shot-analysis-active-filters/);
assert.doesNotMatch(css, /\.analysis-points-tappable/);
assert.match(detailCss, /\.detail-stat-view-seg \.detail-stat-view-btn\.unsaved\.active/);
assert.doesNotMatch(detailCss, /\.detail-stat-view-seg \.detail-stat-view-btn\.active \{/);
assert.match(detailCss, /border: 2px solid #ffffff/);
assert.match(css, /\.btn\[aria-pressed="true"\]/);
assert.match(calculations, /running_shot: "ランニングシュート"/);
assert.match(calculations, /shot\.shotType === "under_basket" \? "jump_shot"/);
assert.match(calculations, /if \(areaId === "backcourt_3p"\) return \["jump_shot"\]/);
assert.match(calculations, /if \(group === "three"\) return \["jump_shot", "running_shot"\]/);
assert.match(calculations, /if \(group === "mid"\) return \["jump_shot", "running_shot", "floater"\]/);
assert.match(calculations, /if \(group === "inside" \|\| group === "under"\) return \["jump_shot", "running_shot", "layup", "floater", "tap"\]/);

console.log("shot UI contract: ok");
