import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync(new URL("../js/app.js", import.meta.url), "utf8");
const css = readFileSync(new URL("../styles/shot-registration.css", import.meta.url), "utf8");

assert.match(app, /selectedShotId=normalizedEditing\?\.id\|\|''/);
assert.match(app, /data-select-shot=/);
assert.match(app, /shot-selection-ring/);
assert.match(app, /shot-foul-ring/);
assert.match(app, /event\.stopPropagation\(\)/);
assert.match(app, /id="shotWasFouled"/);
assert.doesNotMatch(app, /data-shot-filter-foul/);
assert.match(app, /\['foul','yes','ファウル'\]/);
assert.doesNotMatch(app, /analysis-points-tappable/);
assert.match(app, /court-analysis-button/);
assert.match(app, />コート分析</);
assert.doesNotMatch(app, /analysis-shot-filter-details/);
assert.match(app, /data-shot-analysis-filter/);
assert.match(app, /analysisQuickFilters/);
assert.match(app, /analysisActiveFilters/);
assert.match(app, /filters\[field\]=filters\[field\]===value\?'':value/);
assert.doesNotMatch(app, /analysisShotTotal/);
assert.match(app, /data-analysis-shot-type/);
assert.match(app, /selectedType/);
assert.match(app, /shot-analysis-conditions/);
assert.match(app, /displayShots=selectedType/);
assert.match(app, /viewBox="0 0 100 108"/);
assert.match(app, /バックコート3P/);
assert.doesNotMatch(app, /data-shot-area="long_range_3p"/);
assert.match(app, /<th>No\.<\/th>/);
assert.match(app, /<div class="section-title">シュート明細<\/div>/);
assert.doesNotMatch(app, /id="shotQuarter"/);
assert.match(app, /data-shot-result="made" disabled>Made/);
assert.match(app, /data-shot-result="missed" disabled>Miss/);
assert.match(app, /button\.disabled=!\(shotX!=null&&shotY!=null&&areaId&&typeId\)/);
assert.match(app, /row\.onclick=\(\)=>onMark\?\./);
assert.match(app, /await persistShotCollections\(gameId,playerId,collections\);statsForm\(gameId,quarter\)/);
assert.match(css, /\.shot-list-row\.selected/);
assert.match(css, /\.shot-foul-ring/);
assert.match(css, /\.shot-selection-ring/);
assert.doesNotMatch(css, /shot-selection-pulse/);
assert.match(css, /\.analysis-shot-heading/);
assert.match(css, /\.shot-analysis-quick-filters/);
assert.match(css, /\.shot-analysis-active-filters/);
assert.doesNotMatch(css, /\.analysis-points-tappable/);

console.log("shot UI contract: ok");
